version: '3.8'

services:
    app:
        container_name: nameit-prod
        image: nameit-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '80:80'
